server:
  port: 8888
  
spring:
  profiles:
    active: true
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://rankey1496@github.com/RanKey1496/ConfigurationProperties.git
          username: rankey1496
          password: creative1496
